"""empty message

Revision ID: 0d8bb89ddd9c
Revises: ab7926b3942f
Create Date: 2017-03-31 15:12:37.123005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d8bb89ddd9c'
down_revision = 'ab7926b3942f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('fb_access_token', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'player', ['fb_access_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_column('player', 'fb_access_token')
    # ### end Alembic commands ###
