"""empty message

Revision ID: ab7926b3942f
Revises: e13dc0c10cb5
Create Date: 2017-03-27 19:21:39.798226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab7926b3942f'
down_revision = 'e13dc0c10cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('name', sa.String(length=120), nullable=False))
    op.drop_index('email', table_name='player')
    op.drop_column('player', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('email', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('email', 'player', ['email'], unique=True)
    op.drop_column('player', 'name')
    # ### end Alembic commands ###
